# Generated by Django 4.1.7 on 2023-02-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_delete_all_schools'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_schools',
            fields=[
                ('school', models.CharField(auto_created=False, primary_key=True, serialize=False, verbose_name='school')),
            ],
        ),
    ]
